from oracle import Oracle
from copy import deepcopy
from board import Board, Position, Outcome

import sys                                              # Find a more elegant way for this (?)
sys.path.append('../')
from quixo.lib.game import Game, Move, Player

SLIDES = [Move.TOP, Move.BOTTOM, Move.LEFT, Move.RIGHT]
BORDER_POSITIONS = [(x, y) for x in range(5) for y in [0, 4]] + [(x, y) for x in [0, 4] for y in range(1, 4)]

def getPossibleMoves(board: Board, idx: int) -> list[tuple[Position, Move]]:
    """returns all the possible moves given a Game object
        that is, a list of tuples (Position, Move)"""
    possible = []
    for p in BORDER_POSITIONS:
        if board[p] == -1 or board[p] == idx:                                #if it is blank (-1) or mine (idx)
            if p[0] == 0:                                                    #in the top row
                if p[1] == 0:
                    possible += [(p, Move.BOTTOM), (p, Move.RIGHT)]
                elif p[1] == 4:
                    possible += [(p, Move.BOTTOM), (p, Move.LEFT)]    
                else:
                    possible += [(p, Move.BOTTOM), (p, Move.LEFT), (p, Move.RIGHT)]    
            elif p[0] == 4:
                if p[1] == 0:
                    possible += [(p, Move.TOP), (p, Move.RIGHT)]            #in the bottom row
                elif p[1] == 4:
                    possible += [(p, Move.TOP), (p, Move.LEFT)]    
                else:
                    possible += [(p, Move.TOP), (p, Move.LEFT), (p, Move.RIGHT)]
            elif p[1] == 0:                                                 #other rows (1,2,3) on left side
                possible += [(p, Move.TOP), (p, Move.BOTTOM), (p, Move.RIGHT)]
            else:                                                           #other rows on right side
                possible += [(p, Move.TOP), (p, Move.LEFT), (p, Move.BOTTOM)]     
    # i know, it is going to be evaluated again by game, but i think we could really save up some time
    assert len(possible) > 0
    return possible


class DelphiPlayer(Player):
    def __init__(self, tree_depth: int = 4) -> None:
        super().__init__()
        self.delphi: Oracle = Oracle() 
        self.episode: list[Board] = [Board]   
        self.depth: int = tree_depth 

    # TODO: implement pruning
    def __max(self, board: Board, idx: int, beta: float = float("inf"), curr_depth: int = 0) -> float:
        if curr_depth >= self.depth:
            return self.delphi.evaluate(board)
        alpha = -float("inf") #smallest positive value in py
        future_boards: list[np.ndarray] = [self.__apply_move(board, p, idx) for p in getPossibleMoves(board, idx)]
        #evaluated: list[float] = [self.__min(b, (idx + 1)%2, curr_depth + 1) for b in future_boards] #to be removed
        evaluated = []
        for b in future_boards:
            tmp = self.__min(b, (idx + 1)%2, alpha, curr_depth + 1)#calculate the smallest value of a board
            if tmp > beta:
                return tmp
            alpha = tmp if tmp > alpha else alpha #update alpha with the biggest value found so far
            evaluated.append(tmp) # add to the list of evaluations
        return max(evaluated)

    def __min(self, board: Board, idx: int, alpha: float = -float("inf"), curr_depth: int = 1) -> float:
        if curr_depth >= self.depth:                                                        # is this needed?
            return self.delphi.evaluate(board)
        beta = float("inf")
        future_boards: list[np.ndarray] = [self.__apply_move(board, p, idx) for p in getPossibleMoves(board, idx)]
        #evaluated: list[float] = [self.__max(b, (idx + 1)%2, curr_depth + 1) for b in future_boards]
        evaluated = []
        for b in future_boards:
            tmp = self.__max(b, (idx + 1)%2, beta, curr_depth + 1)
            if tmp < alpha: #if we find a value smaller than alpha we stop and we return this value
                return tmp
            beta = tmp if tmp < beta else beta #update beta 
            evaluated.append(tmp)
        return min(evaluated)
    
    def __apply_move(self, board: Board, move: tuple[Position, Move], idx: int) -> Board:
        """gives out a copy of the board after the move is applied
            given a board, a valid move and the player index 
            valid move should be one generated by getPossibleMoves"""
        boardcopy: Board = deepcopy(board)
        boardcopy[move[0]] = idx                            # take the piece
        return self.__slide(boardcopy, move)                # slide the pieces

    # TODO: test, i copied from the game.py and adapted it
    def __slide(self, board: Board, move: tuple[Position, Move]):
        from_pos = move[0]
        slide = move[1]
        piece = board[from_pos]
        # if the player wants to slide it to the left
        if slide == Move.LEFT:
            # for each column starting from the column of the piece and moving to the left
            for i in range(from_pos[1], 0, -1):
            # copy the value contained in the same row and the previous column
                board[(from_pos[0], i)] = board[(
                    from_pos[0], i - 1)]
            # move the piece to the left
            board[(from_pos[0], 0)] = piece
        # if the player wants to slide it to the right
        elif slide == Move.RIGHT:
            # for each column starting from the column of the piece and moving to the right
            for i in range(from_pos[1], board.shape[1] - 1, 1):
                # copy the value contained in the same row and the following column
                board[(from_pos[0], i)] = board[(
                    from_pos[0], i + 1)]
            # move the piece to the right
            board[(from_pos[0], board.shape[1] - 1)] = piece
        # if the player wants to slide it upward
        elif slide == Move.TOP:
            # for each row starting from the row of the piece and going upward
            for i in range(from_pos[0], 0, -1):
                # copy the value contained in the same column and the previous row
                board[(i, from_pos[1])] = board[(
                    i - 1, from_pos[1])]
            # move the piece up
            board[(0, from_pos[1])] = piece
        # if the player wants to slide it downward
        elif slide == Move.BOTTOM:
            # for each row starting from the row of the piece and going downward
            for i in range(from_pos[0], board.shape[0] - 1, 1):
                # copy the value contained in the same column and the following row
                board[(i, from_pos[1])] = board[(
                    i + 1, from_pos[1])]
            # move the piece down
            board[(board.shape[0] - 1, from_pos[1])] = piece        
        return board

    # TODO: implement pruning
    def make_move(self, game: 'Game') -> tuple[tuple[int, int], Move]:
        idx: int = game.get_current_player()
        moves: list[tuple[Position, Move]] = [p for p in getPossibleMoves(game.get_board(), idx)]
        future_boards: list[Board] = [self.__apply_move(game.get_board(), p, idx) for p in moves]
        evaluated: list[tuple[Board, float, tuple[Position, Move]]] = [(b, self.__min(b, (idx + 1)%2), p) for b, p in zip(future_boards, moves)]
        chosen: tuple[Board, float, tuple[Position, Move]] = max(evaluated, key = lambda move_qual: move_qual[1])
        self.episode.append(self.__apply_move(chosen[0], chosen[2], idx))      
        print(chosen)
        return chosen[2]
    
    def feedback(self, outcome: Outcome) -> None:
        """at the end of a game, gives feedback to the oracle"""
        self.delphi.train(self.episode, outcome)
        self.episode = []    

    

# TODO: remove this
if __name__ == '__main__':
    # used for testing  

    dp = DelphiPlayer()
    g = Game()

    # informal test getPossibleMoves
    if False:
        b = g.get_board()
        for s in BORDER_POSITIONS:
            b[s] = 0
        b[0,0] = 1    
        print(b)
        print(len(getPossibleMoves(b, 1)))

    if True:
        g.play(dp, dp)
        g.print()
        print(g.check_winner())